#### Conv-TasNet Setting
name: Conv_Tasnet_with_skip
#gpu_ids: [1,2,3,4,5,6,7]
gpu_ids: [0]
epochs: 100

#### Dataset Configure
datasets:
  num_workers: 5
  batch_size: 1
  fs: 8000
  chunk_len: 4
  chunk_size: 32000   #### fs*chunk_len ####
  train:
    mix_scp: /home/mguerzoni/Conv-TasNet/Conv_TasNet_Pytorch/tr_mix.scp
    ref_scp:
      - /home/mguerzoni/Conv-TasNet/Conv_TasNet_Pytorch/tr_s1.scp
      - /home/mguerzoni/Conv-TasNet/Conv_TasNet_Pytorch/tr_s2.scp
    #sr: 8000
  val:
    mix_scp: /home/mguerzoni/Conv-TasNet/Conv_TasNet_Pytorch/cv_mix.scp
    ref_scp:
      - /home/mguerzoni/Conv-TasNet/Conv_TasNet_Pytorch/cv_s1.scp
      - /home/mguerzoni/Conv-TasNet/Conv_TasNet_Pytorch/cv_s2.scp
    #sr: 8000

#### training settings: learning rate scheme, loss
train:
  optimizer: adam
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5
  logging_period: 200
  clip_norm: ~
  num_epochs: 100
  checkpoint: Conv-TasNet-with-skip

optimizer_kwargs:
  lr: !!float 1e-3
  weight_decay: !!float 1e-5

#### network configure
net_conf:
  N: 512
  L: 16
  B: 128
  H: 512
  P: 3
  X: 1
  R: 1
  norm: gln
  num_spks: 2
  activate: sigmoid
  causal: false

#### resume model
resume:
  path: /home/mguerzoni/Conv-TasNet
  resume_state: false
